// GENERATED DATA - do not edit by hand.
//
// ISO-4217 currency metadata (display name, fraction digits and symbol) mirroring
// `java.util.Currency` as used by the original Android app, captured for the
// `en-US` locale. Dart has no equivalent platform currency registry, so the table
// is bundled to keep currency names, symbols and the picker list identical.

/// Display name, default fraction digits and symbol for one currency code.
class CurrencyInfo {
  const CurrencyInfo(this.displayName, this.fractionDigits, this.symbol);

  final String displayName;
  final int fractionDigits;
  final String symbol;
}

/// Every currency code known to the app, keyed by ISO-4217 code.
const Map<String, CurrencyInfo> kCurrencies = <String, CurrencyInfo>{
  'ADP': CurrencyInfo('Andorran Peseta', 0, 'ADP'),
  'AED': CurrencyInfo('United Arab Emirates Dirham', 2, 'AED'),
  'AFA': CurrencyInfo('Afghan Afghani (1927–2002)', 2, 'AFA'),
  'AFN': CurrencyInfo('Afghan Afghani', 2, 'AFN'),
  'ALL': CurrencyInfo('Albanian Lek', 2, 'ALL'),
  'AMD': CurrencyInfo('Armenian Dram', 2, 'AMD'),
  'ANG': CurrencyInfo('Netherlands Antillean Guilder', 2, 'ANG'),
  'AOA': CurrencyInfo('Angolan Kwanza', 2, 'AOA'),
  'ARS': CurrencyInfo('Argentine Peso', 2, 'ARS'),
  'ATS': CurrencyInfo('Austrian Schilling', 2, 'ATS'),
  'AUD': CurrencyInfo('Australian Dollar', 2, 'A\$'),
  'AWG': CurrencyInfo('Aruban Florin', 2, 'AWG'),
  'AYM': CurrencyInfo('AYM', 2, 'AYM'),
  'AZM': CurrencyInfo('Azerbaijani Manat (1993–2006)', 2, 'AZM'),
  'AZN': CurrencyInfo('Azerbaijani Manat', 2, 'AZN'),
  'BAM': CurrencyInfo('Bosnia-Herzegovina Convertible Mark', 2, 'BAM'),
  'BBD': CurrencyInfo('Barbadian Dollar', 2, 'BBD'),
  'BDT': CurrencyInfo('Bangladeshi Taka', 2, 'BDT'),
  'BEF': CurrencyInfo('Belgian Franc', 0, 'BEF'),
  'BGL': CurrencyInfo('Bulgarian Hard Lev', 2, 'BGL'),
  'BGN': CurrencyInfo('Bulgarian Lev', 2, 'BGN'),
  'BHD': CurrencyInfo('Bahraini Dinar', 3, 'BHD'),
  'BIF': CurrencyInfo('Burundian Franc', 0, 'BIF'),
  'BMD': CurrencyInfo('Bermudan Dollar', 2, 'BMD'),
  'BND': CurrencyInfo('Brunei Dollar', 2, 'BND'),
  'BOB': CurrencyInfo('Bolivian Boliviano', 2, 'BOB'),
  'BOV': CurrencyInfo('Bolivian Mvdol', 2, 'BOV'),
  'BRL': CurrencyInfo('Brazilian Real', 2, 'R\$'),
  'BSD': CurrencyInfo('Bahamian Dollar', 2, 'BSD'),
  'BTN': CurrencyInfo('Bhutanese Ngultrum', 2, 'BTN'),
  'BWP': CurrencyInfo('Botswanan Pula', 2, 'BWP'),
  'BYB': CurrencyInfo('Belarusian Ruble (1994–1999)', 0, 'BYB'),
  'BYN': CurrencyInfo('Belarusian Ruble', 2, 'BYN'),
  'BYR': CurrencyInfo('Belarusian Ruble (2000–2016)', 0, 'BYR'),
  'BZD': CurrencyInfo('Belize Dollar', 2, 'BZD'),
  'CAD': CurrencyInfo('Canadian Dollar', 2, 'CA\$'),
  'CDF': CurrencyInfo('Congolese Franc', 2, 'CDF'),
  'CHE': CurrencyInfo('WIR Euro', 2, 'CHE'),
  'CHF': CurrencyInfo('Swiss Franc', 2, 'CHF'),
  'CHW': CurrencyInfo('WIR Franc', 2, 'CHW'),
  'CLF': CurrencyInfo('Chilean Unit of Account (UF)', 4, 'CLF'),
  'CLP': CurrencyInfo('Chilean Peso', 0, 'CLP'),
  'CNY': CurrencyInfo('Chinese Yuan', 2, 'CN¥'),
  'COP': CurrencyInfo('Colombian Peso', 2, 'COP'),
  'COU': CurrencyInfo('Colombian Real Value Unit', 2, 'COU'),
  'CRC': CurrencyInfo('Costa Rican Colón', 2, 'CRC'),
  'CSD': CurrencyInfo('Serbian Dinar (2002–2006)', 2, 'CSD'),
  'CUC': CurrencyInfo('Cuban Convertible Peso', 2, 'CUC'),
  'CUP': CurrencyInfo('Cuban Peso', 2, 'CUP'),
  'CVE': CurrencyInfo('Cape Verdean Escudo', 2, 'CVE'),
  'CYP': CurrencyInfo('Cypriot Pound', 2, 'CYP'),
  'CZK': CurrencyInfo('Czech Koruna', 2, 'CZK'),
  'DEM': CurrencyInfo('German Mark', 2, 'DEM'),
  'DJF': CurrencyInfo('Djiboutian Franc', 0, 'DJF'),
  'DKK': CurrencyInfo('Danish Krone', 2, 'DKK'),
  'DOP': CurrencyInfo('Dominican Peso', 2, 'DOP'),
  'DZD': CurrencyInfo('Algerian Dinar', 2, 'DZD'),
  'EEK': CurrencyInfo('Estonian Kroon', 2, 'EEK'),
  'EGP': CurrencyInfo('Egyptian Pound', 2, 'EGP'),
  'ERN': CurrencyInfo('Eritrean Nakfa', 2, 'ERN'),
  'ESP': CurrencyInfo('Spanish Peseta', 0, 'ESP'),
  'ETB': CurrencyInfo('Ethiopian Birr', 2, 'ETB'),
  'EUR': CurrencyInfo('Euro', 2, '€'),
  'FIM': CurrencyInfo('Finnish Markka', 2, 'FIM'),
  'FJD': CurrencyInfo('Fijian Dollar', 2, 'FJD'),
  'FKP': CurrencyInfo('Falkland Islands Pound', 2, 'FKP'),
  'FRF': CurrencyInfo('French Franc', 2, 'FRF'),
  'GBP': CurrencyInfo('British Pound', 2, '£'),
  'GEL': CurrencyInfo('Georgian Lari', 2, 'GEL'),
  'GHC': CurrencyInfo('Ghanaian Cedi (1979–2007)', 2, 'GHC'),
  'GHS': CurrencyInfo('Ghanaian Cedi', 2, 'GHS'),
  'GIP': CurrencyInfo('Gibraltar Pound', 2, 'GIP'),
  'GMD': CurrencyInfo('Gambian Dalasi', 2, 'GMD'),
  'GNF': CurrencyInfo('Guinean Franc', 0, 'GNF'),
  'GRD': CurrencyInfo('Greek Drachma', 0, 'GRD'),
  'GTQ': CurrencyInfo('Guatemalan Quetzal', 2, 'GTQ'),
  'GWP': CurrencyInfo('Guinea-Bissau Peso', 2, 'GWP'),
  'GYD': CurrencyInfo('Guyanaese Dollar', 2, 'GYD'),
  'HKD': CurrencyInfo('Hong Kong Dollar', 2, 'HK\$'),
  'HNL': CurrencyInfo('Honduran Lempira', 2, 'HNL'),
  'HRK': CurrencyInfo('Croatian Kuna', 2, 'HRK'),
  'HTG': CurrencyInfo('Haitian Gourde', 2, 'HTG'),
  'HUF': CurrencyInfo('Hungarian Forint', 2, 'HUF'),
  'IDR': CurrencyInfo('Indonesian Rupiah', 2, 'IDR'),
  'IEP': CurrencyInfo('Irish Pound', 2, 'IEP'),
  'ILS': CurrencyInfo('Israeli New Shekel', 2, '₪'),
  'INR': CurrencyInfo('Indian Rupee', 2, '₹'),
  'IQD': CurrencyInfo('Iraqi Dinar', 3, 'IQD'),
  'IRR': CurrencyInfo('Iranian Rial', 2, 'IRR'),
  'ISK': CurrencyInfo('Icelandic Króna', 0, 'ISK'),
  'ITL': CurrencyInfo('Italian Lira', 0, 'ITL'),
  'JMD': CurrencyInfo('Jamaican Dollar', 2, 'JMD'),
  'JOD': CurrencyInfo('Jordanian Dinar', 3, 'JOD'),
  'JPY': CurrencyInfo('Japanese Yen', 0, '¥'),
  'KES': CurrencyInfo('Kenyan Shilling', 2, 'KES'),
  'KGS': CurrencyInfo('Kyrgystani Som', 2, 'KGS'),
  'KHR': CurrencyInfo('Cambodian Riel', 2, 'KHR'),
  'KMF': CurrencyInfo('Comorian Franc', 0, 'KMF'),
  'KPW': CurrencyInfo('North Korean Won', 2, 'KPW'),
  'KRW': CurrencyInfo('South Korean Won', 0, '₩'),
  'KWD': CurrencyInfo('Kuwaiti Dinar', 3, 'KWD'),
  'KYD': CurrencyInfo('Cayman Islands Dollar', 2, 'KYD'),
  'KZT': CurrencyInfo('Kazakhstani Tenge', 2, 'KZT'),
  'LAK': CurrencyInfo('Laotian Kip', 2, 'LAK'),
  'LBP': CurrencyInfo('Lebanese Pound', 2, 'LBP'),
  'LKR': CurrencyInfo('Sri Lankan Rupee', 2, 'LKR'),
  'LRD': CurrencyInfo('Liberian Dollar', 2, 'LRD'),
  'LSL': CurrencyInfo('Lesotho Loti', 2, 'LSL'),
  'LTL': CurrencyInfo('Lithuanian Litas', 2, 'LTL'),
  'LUF': CurrencyInfo('Luxembourgian Franc', 0, 'LUF'),
  'LVL': CurrencyInfo('Latvian Lats', 2, 'LVL'),
  'LYD': CurrencyInfo('Libyan Dinar', 3, 'LYD'),
  'MAD': CurrencyInfo('Moroccan Dirham', 2, 'MAD'),
  'MDL': CurrencyInfo('Moldovan Leu', 2, 'MDL'),
  'MGA': CurrencyInfo('Malagasy Ariary', 2, 'MGA'),
  'MGF': CurrencyInfo('Malagasy Franc', 0, 'MGF'),
  'MKD': CurrencyInfo('Macedonian Denar', 2, 'MKD'),
  'MMK': CurrencyInfo('Myanmar Kyat', 2, 'MMK'),
  'MNT': CurrencyInfo('Mongolian Tugrik', 2, 'MNT'),
  'MOP': CurrencyInfo('Macanese Pataca', 2, 'MOP'),
  'MRO': CurrencyInfo('Mauritanian Ouguiya (1973–2017)', 2, 'MRO'),
  'MRU': CurrencyInfo('Mauritanian Ouguiya', 2, 'MRU'),
  'MTL': CurrencyInfo('Maltese Lira', 2, 'MTL'),
  'MUR': CurrencyInfo('Mauritian Rupee', 2, 'MUR'),
  'MVR': CurrencyInfo('Maldivian Rufiyaa', 2, 'MVR'),
  'MWK': CurrencyInfo('Malawian Kwacha', 2, 'MWK'),
  'MXN': CurrencyInfo('Mexican Peso', 2, 'MX\$'),
  'MXV': CurrencyInfo('Mexican Investment Unit', 2, 'MXV'),
  'MYR': CurrencyInfo('Malaysian Ringgit', 2, 'MYR'),
  'MZM': CurrencyInfo('Mozambican Metical (1980–2006)', 2, 'MZM'),
  'MZN': CurrencyInfo('Mozambican Metical', 2, 'MZN'),
  'NAD': CurrencyInfo('Namibian Dollar', 2, 'NAD'),
  'NGN': CurrencyInfo('Nigerian Naira', 2, 'NGN'),
  'NIO': CurrencyInfo('Nicaraguan Córdoba', 2, 'NIO'),
  'NLG': CurrencyInfo('Dutch Guilder', 2, 'NLG'),
  'NOK': CurrencyInfo('Norwegian Krone', 2, 'NOK'),
  'NPR': CurrencyInfo('Nepalese Rupee', 2, 'NPR'),
  'NZD': CurrencyInfo('New Zealand Dollar', 2, 'NZ\$'),
  'OMR': CurrencyInfo('Omani Rial', 3, 'OMR'),
  'PAB': CurrencyInfo('Panamanian Balboa', 2, 'PAB'),
  'PEN': CurrencyInfo('Peruvian Sol', 2, 'PEN'),
  'PGK': CurrencyInfo('Papua New Guinean Kina', 2, 'PGK'),
  'PHP': CurrencyInfo('Philippine Piso', 2, '₱'),
  'PKR': CurrencyInfo('Pakistani Rupee', 2, 'PKR'),
  'PLN': CurrencyInfo('Polish Zloty', 2, 'PLN'),
  'PTE': CurrencyInfo('Portuguese Escudo', 0, 'PTE'),
  'PYG': CurrencyInfo('Paraguayan Guarani', 0, 'PYG'),
  'QAR': CurrencyInfo('Qatari Rial', 2, 'QAR'),
  'ROL': CurrencyInfo('Romanian Leu (1952–2006)', 0, 'ROL'),
  'RON': CurrencyInfo('Romanian Leu', 2, 'RON'),
  'RSD': CurrencyInfo('Serbian Dinar', 2, 'RSD'),
  'RUB': CurrencyInfo('Russian Ruble', 2, 'RUB'),
  'RUR': CurrencyInfo('Russian Ruble (1991–1998)', 2, 'RUR'),
  'RWF': CurrencyInfo('Rwandan Franc', 0, 'RWF'),
  'SAR': CurrencyInfo('Saudi Riyal', 2, 'SAR'),
  'SBD': CurrencyInfo('Solomon Islands Dollar', 2, 'SBD'),
  'SCR': CurrencyInfo('Seychellois Rupee', 2, 'SCR'),
  'SDD': CurrencyInfo('Sudanese Dinar (1992–2007)', 2, 'SDD'),
  'SDG': CurrencyInfo('Sudanese Pound', 2, 'SDG'),
  'SEK': CurrencyInfo('Swedish Krona', 2, 'SEK'),
  'SGD': CurrencyInfo('Singapore Dollar', 2, 'SGD'),
  'SHP': CurrencyInfo('St. Helena Pound', 2, 'SHP'),
  'SIT': CurrencyInfo('Slovenian Tolar', 2, 'SIT'),
  'SKK': CurrencyInfo('Slovak Koruna', 2, 'SKK'),
  'SLE': CurrencyInfo('Sierra Leonean Leone', 2, 'SLE'),
  'SLL': CurrencyInfo('Sierra Leonean Leone', 2, 'SLL'),
  'SOS': CurrencyInfo('Somali Shilling', 2, 'SOS'),
  'SRD': CurrencyInfo('Surinamese Dollar', 2, 'SRD'),
  'SRG': CurrencyInfo('Surinamese Guilder', 2, 'SRG'),
  'SSP': CurrencyInfo('South Sudanese Pound', 2, 'SSP'),
  'STD': CurrencyInfo('São Tomé & Príncipe Dobra (1977–2017)', 2, 'STD'),
  'STN': CurrencyInfo('São Tomé & Príncipe Dobra', 2, 'STN'),
  'SVC': CurrencyInfo('Salvadoran Colón', 2, 'SVC'),
  'SYP': CurrencyInfo('Syrian Pound', 2, 'SYP'),
  'SZL': CurrencyInfo('Swazi Lilangeni', 2, 'SZL'),
  'THB': CurrencyInfo('Thai Baht', 2, 'THB'),
  'TJS': CurrencyInfo('Tajikistani Somoni', 2, 'TJS'),
  'TMM': CurrencyInfo('Turkmenistani Manat (1993–2009)', 2, 'TMM'),
  'TMT': CurrencyInfo('Turkmenistani Manat', 2, 'TMT'),
  'TND': CurrencyInfo('Tunisian Dinar', 3, 'TND'),
  'TOP': CurrencyInfo('Tongan Paʻanga', 2, 'TOP'),
  'TPE': CurrencyInfo('Timorese Escudo', 0, 'TPE'),
  'TRL': CurrencyInfo('Turkish Lira (1922–2005)', 0, 'TRL'),
  'TRY': CurrencyInfo('Turkish Lira', 2, 'TRY'),
  'TTD': CurrencyInfo('Trinidad & Tobago Dollar', 2, 'TTD'),
  'TWD': CurrencyInfo('New Taiwan Dollar', 2, 'NT\$'),
  'TZS': CurrencyInfo('Tanzanian Shilling', 2, 'TZS'),
  'UAH': CurrencyInfo('Ukrainian Hryvnia', 2, 'UAH'),
  'UGX': CurrencyInfo('Ugandan Shilling', 0, 'UGX'),
  'USD': CurrencyInfo('US Dollar', 2, '\$'),
  'USN': CurrencyInfo('US Dollar (Next day)', 2, 'USN'),
  'USS': CurrencyInfo('US Dollar (Same day)', 2, 'USS'),
  'UYI': CurrencyInfo('Uruguayan Peso (Indexed Units)', 0, 'UYI'),
  'UYU': CurrencyInfo('Uruguayan Peso', 2, 'UYU'),
  'UZS': CurrencyInfo('Uzbekistani Som', 2, 'UZS'),
  'VEB': CurrencyInfo('Venezuelan Bolívar (1871–2008)', 2, 'VEB'),
  'VED': CurrencyInfo('Venezuelan Bolívar Soberano', 2, 'VED'),
  'VEF': CurrencyInfo('Venezuelan Bolívar (2008–2018)', 2, 'VEF'),
  'VES': CurrencyInfo('Venezuelan Bolívar', 2, 'VES'),
  'VND': CurrencyInfo('Vietnamese Dong', 0, '₫'),
  'VUV': CurrencyInfo('Vanuatu Vatu', 0, 'VUV'),
  'WST': CurrencyInfo('Samoan Tala', 2, 'WST'),
  'XAD': CurrencyInfo('Arab Accounting Dinar', 2, 'XAD'),
  'XAF': CurrencyInfo('Central African CFA Franc', 0, 'FCFA'),
  'XAG': CurrencyInfo('Silver', 0, 'XAG'),
  'XAU': CurrencyInfo('Gold', 0, 'XAU'),
  'XBA': CurrencyInfo('European Composite Unit', 0, 'XBA'),
  'XBB': CurrencyInfo('European Monetary Unit', 0, 'XBB'),
  'XBC': CurrencyInfo('European Unit of Account (XBC)', 0, 'XBC'),
  'XBD': CurrencyInfo('European Unit of Account (XBD)', 0, 'XBD'),
  'XCD': CurrencyInfo('East Caribbean Dollar', 2, 'EC\$'),
  'XCG': CurrencyInfo('Caribbean Guilder', 2, 'XCG'),
  'XDR': CurrencyInfo('Special Drawing Rights', 0, 'XDR'),
  'XFO': CurrencyInfo('French Gold Franc', 0, 'XFO'),
  'XFU': CurrencyInfo('French UIC-Franc', 0, 'XFU'),
  'XOF': CurrencyInfo('West African CFA Franc', 0, 'F CFA'),
  'XPD': CurrencyInfo('Palladium', 0, 'XPD'),
  'XPF': CurrencyInfo('CFP Franc', 0, 'CFPF'),
  'XPT': CurrencyInfo('Platinum', 0, 'XPT'),
  'XSU': CurrencyInfo('Sucre', 0, 'XSU'),
  'XTS': CurrencyInfo('Testing Currency Code', 0, 'XTS'),
  'XUA': CurrencyInfo('ADB Unit of Account', 0, 'XUA'),
  'XXX': CurrencyInfo('Unknown Currency', 0, '¤'),
  'YER': CurrencyInfo('Yemeni Rial', 2, 'YER'),
  'YUM': CurrencyInfo('Yugoslavian New Dinar (1994–2002)', 2, 'YUM'),
  'ZAR': CurrencyInfo('South African Rand', 2, 'ZAR'),
  'ZMK': CurrencyInfo('Zambian Kwacha (1968–2012)', 2, 'ZMK'),
  'ZMW': CurrencyInfo('Zambian Kwacha', 2, 'ZMW'),
  'ZWD': CurrencyInfo('Zimbabwean Dollar (1980–2008)', 2, 'ZWD'),
  'ZWG': CurrencyInfo('Zimbabwe Gold', 2, 'ZWG'),
  'ZWL': CurrencyInfo('Zimbabwean Dollar (2009)', 2, 'ZWL'),
  'ZWN': CurrencyInfo('ZWN', 2, 'ZWN'),
  'ZWR': CurrencyInfo('Zimbabwean Dollar (2008)', 2, 'ZWR'),
};

/// ISO-3166 country code to the currency used there, for the device default.
const Map<String, String> kCountryCurrencies = <String, String>{
  'AD': 'EUR',
  'AE': 'AED',
  'AF': 'AFN',
  'AG': 'XCD',
  'AI': 'XCD',
  'AL': 'ALL',
  'AM': 'AMD',
  'AO': 'AOA',
  'AR': 'ARS',
  'AS': 'USD',
  'AT': 'EUR',
  'AU': 'AUD',
  'AW': 'AWG',
  'AX': 'EUR',
  'AZ': 'AZN',
  'BA': 'BAM',
  'BB': 'BBD',
  'BD': 'BDT',
  'BE': 'EUR',
  'BF': 'XOF',
  'BG': 'EUR',
  'BH': 'BHD',
  'BI': 'BIF',
  'BJ': 'XOF',
  'BL': 'EUR',
  'BM': 'BMD',
  'BN': 'BND',
  'BO': 'BOB',
  'BQ': 'USD',
  'BR': 'BRL',
  'BS': 'BSD',
  'BT': 'BTN',
  'BV': 'NOK',
  'BW': 'BWP',
  'BY': 'BYN',
  'BZ': 'BZD',
  'CA': 'CAD',
  'CC': 'AUD',
  'CD': 'CDF',
  'CF': 'XAF',
  'CG': 'XAF',
  'CH': 'CHF',
  'CI': 'XOF',
  'CK': 'NZD',
  'CL': 'CLP',
  'CM': 'XAF',
  'CN': 'CNY',
  'CO': 'COP',
  'CR': 'CRC',
  'CU': 'CUP',
  'CV': 'CVE',
  'CW': 'XCG',
  'CX': 'AUD',
  'CY': 'EUR',
  'CZ': 'CZK',
  'DE': 'EUR',
  'DJ': 'DJF',
  'DK': 'DKK',
  'DM': 'XCD',
  'DO': 'DOP',
  'DZ': 'DZD',
  'EC': 'USD',
  'EE': 'EUR',
  'EG': 'EGP',
  'EH': 'MAD',
  'ER': 'ERN',
  'ES': 'EUR',
  'ET': 'ETB',
  'FI': 'EUR',
  'FJ': 'FJD',
  'FK': 'FKP',
  'FM': 'USD',
  'FO': 'DKK',
  'FR': 'EUR',
  'GA': 'XAF',
  'GB': 'GBP',
  'GD': 'XCD',
  'GE': 'GEL',
  'GF': 'EUR',
  'GG': 'GBP',
  'GH': 'GHS',
  'GI': 'GIP',
  'GL': 'DKK',
  'GM': 'GMD',
  'GN': 'GNF',
  'GP': 'EUR',
  'GQ': 'XAF',
  'GR': 'EUR',
  'GS': 'GBP',
  'GT': 'GTQ',
  'GU': 'USD',
  'GW': 'XOF',
  'GY': 'GYD',
  'HK': 'HKD',
  'HM': 'AUD',
  'HN': 'HNL',
  'HR': 'EUR',
  'HT': 'HTG',
  'HU': 'HUF',
  'ID': 'IDR',
  'IE': 'EUR',
  'IL': 'ILS',
  'IM': 'GBP',
  'IN': 'INR',
  'IO': 'USD',
  'IQ': 'IQD',
  'IR': 'IRR',
  'IS': 'ISK',
  'IT': 'EUR',
  'JE': 'GBP',
  'JM': 'JMD',
  'JO': 'JOD',
  'JP': 'JPY',
  'KE': 'KES',
  'KG': 'KGS',
  'KH': 'KHR',
  'KI': 'AUD',
  'KM': 'KMF',
  'KN': 'XCD',
  'KP': 'KPW',
  'KR': 'KRW',
  'KW': 'KWD',
  'KY': 'KYD',
  'KZ': 'KZT',
  'LA': 'LAK',
  'LB': 'LBP',
  'LC': 'XCD',
  'LI': 'CHF',
  'LK': 'LKR',
  'LR': 'LRD',
  'LS': 'LSL',
  'LT': 'EUR',
  'LU': 'EUR',
  'LV': 'EUR',
  'LY': 'LYD',
  'MA': 'MAD',
  'MC': 'EUR',
  'MD': 'MDL',
  'ME': 'EUR',
  'MF': 'EUR',
  'MG': 'MGA',
  'MH': 'USD',
  'MK': 'MKD',
  'ML': 'XOF',
  'MM': 'MMK',
  'MN': 'MNT',
  'MO': 'MOP',
  'MP': 'USD',
  'MQ': 'EUR',
  'MR': 'MRU',
  'MS': 'XCD',
  'MT': 'EUR',
  'MU': 'MUR',
  'MV': 'MVR',
  'MW': 'MWK',
  'MX': 'MXN',
  'MY': 'MYR',
  'MZ': 'MZN',
  'NA': 'NAD',
  'NC': 'XPF',
  'NE': 'XOF',
  'NF': 'AUD',
  'NG': 'NGN',
  'NI': 'NIO',
  'NL': 'EUR',
  'NO': 'NOK',
  'NP': 'NPR',
  'NR': 'AUD',
  'NU': 'NZD',
  'NZ': 'NZD',
  'OM': 'OMR',
  'PA': 'PAB',
  'PE': 'PEN',
  'PF': 'XPF',
  'PG': 'PGK',
  'PH': 'PHP',
  'PK': 'PKR',
  'PL': 'PLN',
  'PM': 'EUR',
  'PN': 'NZD',
  'PR': 'USD',
  'PS': 'ILS',
  'PT': 'EUR',
  'PW': 'USD',
  'PY': 'PYG',
  'QA': 'QAR',
  'RE': 'EUR',
  'RO': 'RON',
  'RS': 'RSD',
  'RU': 'RUB',
  'RW': 'RWF',
  'SA': 'SAR',
  'SB': 'SBD',
  'SC': 'SCR',
  'SD': 'SDG',
  'SE': 'SEK',
  'SG': 'SGD',
  'SH': 'SHP',
  'SI': 'EUR',
  'SJ': 'NOK',
  'SK': 'EUR',
  'SL': 'SLE',
  'SM': 'EUR',
  'SN': 'XOF',
  'SO': 'SOS',
  'SR': 'SRD',
  'SS': 'SSP',
  'ST': 'STN',
  'SV': 'SVC',
  'SX': 'XCG',
  'SY': 'SYP',
  'SZ': 'SZL',
  'TC': 'USD',
  'TD': 'XAF',
  'TF': 'EUR',
  'TG': 'XOF',
  'TH': 'THB',
  'TJ': 'TJS',
  'TK': 'NZD',
  'TL': 'USD',
  'TM': 'TMT',
  'TN': 'TND',
  'TO': 'TOP',
  'TR': 'TRY',
  'TT': 'TTD',
  'TV': 'AUD',
  'TW': 'TWD',
  'TZ': 'TZS',
  'UA': 'UAH',
  'UG': 'UGX',
  'UM': 'USD',
  'US': 'USD',
  'UY': 'UYU',
  'UZ': 'UZS',
  'VA': 'EUR',
  'VC': 'XCD',
  'VE': 'VES',
  'VG': 'USD',
  'VI': 'USD',
  'VN': 'VND',
  'VU': 'VUV',
  'WF': 'XPF',
  'WS': 'WST',
  'YE': 'YER',
  'YT': 'EUR',
  'ZA': 'ZAR',
  'ZM': 'ZMW',
  'ZW': 'ZWG',
};
